/**
 * Shared Convex validators.
 *
 * Every literal here MUST mirror the union of `Product.category`,
 * `Order.status`, the colour-gradient keys, etc. used by the frontend so
 * that documents written by the seed (or any future admin) validate
 * end-to-end.
 *
 * `v.*` validators come from `convex/values`. The `Infer<...>` type
 * is generated by Convex and re-exported from
 * `convex/_generated/dataModel`.
 */
import { v } from "convex/values";

// ----------------------------------------------------------------
// Product taxonomy
// ----------------------------------------------------------------

export const productCategoryLiterals = [
  "bras",
  "briefs",
  "sets",
  "sleepwear",
  "loungewear",
  "bodysuits",
  "shapewear",
  "sportswear",
  "accessories",
  "bridal",
] as const;

export const vProductCategory = v.union(
  ...productCategoryLiterals.map((c) => v.literal(c))
);

// The five gradient "tones" used by `src/lib/glass.ts` and the
// product image placeholders. Keep these in sync.
export const gradientLiterals = ["mist", "oat", "rose", "deep", "ivory", "pearl"] as const;
export const vGradient = v.union(...gradientLiterals.map((g) => v.literal(g)));

export const badgeLiterals = [
  "new",
  "restocked",
  "limited",
  "editorial",
  "exclusive",
] as const;
export const vBadge = v.union(...badgeLiterals.map((b) => v.literal(b)));

export const productStatusLiterals = ["draft", "published", "archived"] as const;
export const vProductStatus = v.union(
  ...productStatusLiterals.map((s) => v.literal(s))
);

export const vColorOption = v.object({
  id: v.string(),
  name: v.string(),
  gradient: vGradient,
});

export const vSizeOption = v.object({
  id: v.string(),
  label: v.string(),
});

// ----------------------------------------------------------------
// Pricing / money
// ----------------------------------------------------------------

// Cents-friendly. The frontend currently prints whole dollars but we
// keep storage in cents to avoid float drift when future payments land.
export const vMoney = v.object({
  // Stored in cents to keep arithmetic exact.
  amount: v.number(),
  currency: v.literal("USD"),
});

// ----------------------------------------------------------------
// Order lifecycle
// ----------------------------------------------------------------

export const orderStatusLiterals = [
  "pending",
  "processing",
  "shipped",
  "delivered",
  "returning",
  "cancelled",
] as const;
export const vOrderStatus = v.union(
  ...orderStatusLiterals.map((s) => v.literal(s))
);

// Mirror of `carts.lines[number]` — productId stays an opaque string
// (catalog ids / slugs), matching the schema.
export const vCartLine = v.object({
  productId: v.string(),
  size: v.string(),
  color: v.string(),
  quantity: v.number(),
  addedAt: v.number(),
});

// ----------------------------------------------------------------
// Editorial / content
// ----------------------------------------------------------------

export const editorialKindLiterals = [
  "journal",
  "atelier",
  "campaign",
  "blog",
] as const;
export const vEditorialKind = v.union(
  ...editorialKindLiterals.map((k) => v.literal(k))
);

// ----------------------------------------------------------------
// Phase 8.1 — payment / reservation / shipping literals
// ----------------------------------------------------------------

export const paymentStatusLiterals = [
  "pending",
  "initiated",
  "redirected",
  "paid",
  "failed",
  "cancelled",
  "refunded",
] as const;
export const vPaymentStatus = v.union(
  ...paymentStatusLiterals.map((s) => v.literal(s))
);

export const reservationStatusLiterals = [
  "active",
  "converted",
  "expired",
  "cancelled",
] as const;
export const vReservationStatus = v.union(
  ...reservationStatusLiterals.map((s) => v.literal(s))
);

export const shippingMethodLiterals = [
  "standard",
  "express",
  "white_glove",
] as const;
export const vShippingMethod = v.union(
  ...shippingMethodLiterals.map((s) => v.literal(s))
);

// ----------------------------------------------------------------
// Roles — Phase 5 extension
// ----------------------------------------------------------------
//
// Phase 5 expands the role literal set so the admin surface can model
// finer-grained access without inventing a separate permissions
// table. The previous literals (`admin`, `member`, `user`) are kept
// for backward compatibility — every existing user row remains valid.
//
// Permission level order (higher index → broader access):
//   owner > admin > manager > editor > support > member > user
//
// Owners are documented but unimplemented — they're reserved for the
// future multi-brand hierarchy. Today every mutation accepts
// owner + admin via `_helpers.assertAdmin` and selectively manager +
// editor + support.
export const roleLiterals = [
  "owner",
  "admin",
  "manager",
  "editor",
  "support",
  "member",
  "user",
] as const;
export const vRole = v.union(...roleLiterals.map((r) => v.literal(r)));

// ----------------------------------------------------------------
// Phase 5 — admin permission unions
// ----------------------------------------------------------------
//
// These are free-floating literals used to drive coarse-grained
// gating on admin routes and mutations. They aren't stored on the
// row — they read `role` and translate. See `convex/_helpers.ts`
// for `hasPermission(role, "manage_products")`.

export const adminPermissionLiterals = [
  "manage_products",
  "manage_inventory",
  "manage_orders",
  "manage_customers",
  "manage_content",
  "manage_coupons",
  "manage_settings",
  "manage_media",
  "view_reports",
] as const;
export type AdminPermission = (typeof adminPermissionLiterals)[number];
