/**
 * Shared Convex validators.
 *
 * Every literal here MUST mirror the union of `Product.category`, `Order.status`,
 * the colour-gradient keys, etc. used by the frontend so that documents written
 * by the seed (or any future admin) validate end-to-end.
 *
 * `v.*` validators come from `convex/values`. The `Infer<...>` type
 * is generated by Convex and re-exported from `convex/_generated/dataModel`.
 */
import { v } from "convex/values";

// ----------------------------------------------------------------
// Product taxonomy
// ----------------------------------------------------------------

export const productCategoryLiterals = [
  "outerwear",
  "knitwear",
  "shirting",
  "trousers",
  "dresses",
  "leather",
  "accessories",
] as const;

export const vProductCategory = v.union(
  ...productCategoryLiterals.map((c) => v.literal(c))
);

// The five gradient "tones" used by `src/lib/glass.ts` and the
// product image placeholders. Keep these in sync.
export const gradientLiterals = ["mist", "oat", "rose", "deep", "ivory"] as const;
export const vGradient = v.union(...gradientLiterals.map((g) => v.literal(g)));

export const badgeLiterals = [
  "new",
  "restocked",
  "limited",
  "editorial",
  "exclusive",
] as const;
export const vBadge = v.union(...badgeLiterals.map((b) => v.literal(b)));

export const productStatusLiterals = ["draft", "published", "archived"] as const;
export const vProductStatus = v.union(
  ...productStatusLiterals.map((s) => v.literal(s))
);

export const vColorOption = v.object({
  id: v.string(),
  name: v.string(),
  gradient: vGradient,
});

export const vSizeOption = v.object({
  id: v.string(),
  label: v.string(),
});

// ----------------------------------------------------------------
// Pricing / money
// ----------------------------------------------------------------

// Cents-friendly. The frontend currently prints whole dollars but we
// keep storage in cents to avoid float drift when future payments land.
export const vMoney = v.object({
  // Stored in cents to keep arithmetic exact.
  amount: v.number(),
  currency: v.literal("USD"),
});

// ----------------------------------------------------------------
// Order lifecycle
// ----------------------------------------------------------------

export const orderStatusLiterals = [
  "pending",
  "processing",
  "shipped",
  "delivered",
  "returning",
  "cancelled",
] as const;
export const vOrderStatus = v.union(
  ...orderStatusLiterals.map((s) => v.literal(s))
);

export const vCartLine = v.object({
  productId: v.id("products"),
  size: v.string(),
  color: v.string(),
  quantity: v.number(),
  addedAt: v.number(),
});

// ----------------------------------------------------------------
// Editorial / content
// ----------------------------------------------------------------

export const editorialKindLiterals = [
  "journal",
  "atelier",
  "campaign",
  "blog",
] as const;
export const vEditorialKind = v.union(
  ...editorialKindLiterals.map((k) => v.literal(k))
);

// ----------------------------------------------------------------
// Roles
// ----------------------------------------------------------------

export const roleLiterals = ["admin", "member", "user"] as const;
export const vRole = v.union(...roleLiterals.map((r) => v.literal(r)));
